export { useValue as get, useEquals as is } from '@composables/useType'

export { is as isArray } from '@/array'
export { is as isAsync } from '@/async'
export { is as isBoolean } from '@/boolean'
export { is as isClosure } from '@/closure'
export { is as isFalse } from '@/false'
export { is as isFunction } from '@/function'
export { is as isGenerator } from '@/generator'
export { is as isInteger } from '@/integer'
export { is as isNaN } from '@/nan'
export { is as isNull } from '@/null'
export { is as isNumber } from '@/number'
export { is as isObject } from '@/object'
export { is as isProxy } from '@/proxy'
export { is as isString } from '@/string'
export { is as isTrue } from '@/true'
export { is as isUndefined } from '@/undefined'
